version: "3.8"

volumes: # 自定义数据卷
  static_vol: #定义数据卷同步存放web项目static文件夹的数据
  media_vol: #定义数据卷同步存放web项目用户上传到media文件夹的数据

# 自定义网络(默认桥接), 不使用links通信
networks:
  beer_net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: rabbitmq
    networks:
      - beer_net
    # 通过挂载数据卷备份rabbitmq数据
    volumes:
      - ./compose/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # always表容器运行发生错误时一直重启
    restart: always
    tty: true
    stdin_open: true

  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql.196652.*
      MYSQL_DATABASE: beer
    networks:
      - beer_net
    volumes:
      - ./compose/mysql/logs:/logs
      - ./compose/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    tty: true
    stdin_open: true

  backend:
    # 项目根目录下的Dockerfile
    build: .
    container_name: backend
    hostname: backend
    # 将django后端收集到的静态文件持久化到本地，供nginx部署时使用
    volumes:
      - static_vol:/root/beer_server/static
      - media_vol:/root/beer_server/media
      - ./compose/server/celery.log:/root/beer_server/celery.log
      - ./compose/server/logs:/root/beer_server/logs
      - ./compose/server/config.ini:/root/beer_server/compose/server/config.ini
    networks:
      - beer_net
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8000:8000"
    restart: always
    tty: true
    stdin_open: true

  nginx:
    build: compose/frontend
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
      - ./compose/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./compose/frontend/nginx_logs:/var/log/nginx
    networks:
      - beer_net
    restart: always
    depends_on:
      - backend
    tty: true
    stdin_open: true