# Generated by Django 3.1.7 on 2021-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teststepvalidator',
            options={'verbose_name': '测试步骤的校验器', 'verbose_name_plural': '测试步骤的校验器'},
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='name',
            new_name='testcase_name',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='name',
            new_name='teststep_name',
        ),
        migrations.AddField(
            model_name='testcase',
            name='testcase_desc',
            field=models.CharField(blank=True, help_text='测试用例描述', max_length=128, verbose_name='测试用例描述'),
        ),
    ]
