# Generated by Django 3.1.7 on 2021-04-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststep',
            name='testcase',
            field=models.ForeignKey(help_text='所属用例', null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcase.testcase', verbose_name='所属用例'),
        ),
    ]
