# Generated by Django 3.2.4 on 2021-06-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('modifier', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('config_name', models.CharField(help_text='配置名称', max_length=150, verbose_name='配置名称')),
                ('config_desc', models.CharField(blank=True, default='', help_text='配置描述', max_length=256, verbose_name='配置描述')),
                ('global_variable', models.JSONField(help_text='全局变量', verbose_name='全局变量')),
                ('project', models.ForeignKey(help_text='所属项目ID', on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='所属项目ID')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'db_table': 'config_info',
            },
        ),
    ]
