# Generated by Django 3.1.7 on 2021-04-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='逻辑删除(值为true表示已删除,为false表示未被删除)', verbose_name='逻辑删除(值为true表示已删除,为false表示未被删除)')),
                ('creator', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('modifier', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('config_name', models.CharField(help_text='配置名称', max_length=150, verbose_name='配置名称')),
                ('config_desc', models.CharField(blank=True, help_text='配置描述', max_length=256, verbose_name='配置描述')),
                ('project', models.ForeignKey(help_text='所属项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'db_table': 'config_info',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_key', models.CharField(blank=True, help_text='全局变量的key', max_length=128, unique=True, verbose_name='全局变量的key')),
                ('var_value', models.TextField(blank=True, help_text='全局变量的value(全局变量值/jmespath表达式)', verbose_name='全局变量的value(全局变量值/jmespath表达式)')),
                ('desc', models.CharField(blank=True, help_text='全局变量描述', max_length=512, verbose_name='全局变量描述')),
                ('config', models.ForeignKey(help_text='所属配置项', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_variables', to='config.config', verbose_name='所属配置项')),
            ],
            options={
                'verbose_name': '全局变量',
                'verbose_name_plural': '全局变量',
                'db_table': 'global_variable_info',
            },
        ),
    ]
