# Generated by Django 3.1.7 on 2021-04-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='project',
        ),
        migrations.AddField(
            model_name='config',
            name='project',
            field=models.ManyToManyField(help_text='关联项目', to='project.Project', verbose_name='关联项目'),
        ),
    ]
