# Generated by Django 3.1.7 on 2021-04-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='逻辑删除(值为true表示已删除,为false表示未被删除)', verbose_name='逻辑删除(值为true表示已删除,为false表示未被删除)')),
                ('creator', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('modifier', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('testsuite_name', models.CharField(help_text='套件名称', max_length=150, verbose_name='套件名称')),
                ('testsuite_desc', models.CharField(blank=True, help_text='套件描述', max_length=256, verbose_name='套件描述')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '套件',
                'verbose_name_plural': '套件',
                'db_table': 'testsuite_info',
            },
        ),
    ]
