# Generated by Django 3.1.7 on 2021-04-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('testsuite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(help_text='所属项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='所属项目'),
        ),
    ]
